import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Providers from "./providers";

const poppins = Poppins({
  weight: ["100","200","300","400","500","600","700","800","900"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className={`${poppins.className} antialiased`}>
        <Providers>
          <header className="w-full h-[70px] flex items-center pl-6">
            {/* Left Header */}
            <div>
              <h1 className="font-medium text-2xl">Task</h1>
            </div>
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
