import type { Metadata } from "next";
import "./globals.css";
import { BoardProvider } from "./contexts/board";
import { ThemeProvider } from "@/components/theme-provider";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["100","200","300","400","500","600","700","800","900"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="pt-br">
      <body className={`${poppins.className} antialiased`}>
        <ThemeProvider
        attribute="class"
        defaultTheme="dark">
          <BoardProvider>
          <header className="w-full h-[70px] flex items-center pl-6">
              {/* Left Header */}
              <div>
                <h1 className="font-medium text-2xl">Tasks</h1>
              </div>
            </header>
            {children}
          </BoardProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
